version: '3.8'

services:
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    ports:
      - "8081:8081"

volumes:
  mongo-data:
